# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConeDialogue.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ConeDialogue(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(400, 300)
        Dialog.setMinimumSize(QtCore.QSize(400, 300))
        Dialog.setMaximumSize(QtCore.QSize(400, 300))
        Dialog.setSizeGripEnabled(False)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.HeightLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.HeightLineEdit.setObjectName("HeightLineEdit")
        self.verticalLayout_4.addWidget(self.HeightLineEdit)
        self.BottomRadiusLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.BottomRadiusLineEdit.setObjectName("BottomRadiusLineEdit")
        self.verticalLayout_4.addWidget(self.BottomRadiusLineEdit)
        self.SideComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.SideComboBox.setEnabled(True)
        self.SideComboBox.setObjectName("SideComboBox")
        self.SideComboBox.addItem("")
        self.SideComboBox.addItem("")
        self.verticalLayout_4.addWidget(self.SideComboBox)
        self.BottomComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.BottomComboBox.setObjectName("BottomComboBox")
        self.BottomComboBox.addItem("")
        self.BottomComboBox.addItem("")
        self.verticalLayout_4.addWidget(self.BottomComboBox)
        self.SolidComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.SolidComboBox.setObjectName("SolidComboBox")
        self.SolidComboBox.addItem("")
        self.SolidComboBox.addItem("")
        self.verticalLayout_4.addWidget(self.SolidComboBox)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Cone Node Dialogue"))
        self.groupBox.setTitle(_translate("Dialog", "Fields"))
        self.label.setText(_translate("Dialog", "Height"))
        self.label_2.setText(_translate("Dialog", "BottomRadius"))
        self.label_3.setText(_translate("Dialog", "Side"))
        self.label_4.setText(_translate("Dialog", "Bottom"))
        self.label_5.setText(_translate("Dialog", "Solid"))
        self.groupBox_2.setTitle(_translate("Dialog", "Value"))
        self.SideComboBox.setItemText(0, _translate("Dialog", "True"))
        self.SideComboBox.setItemText(1, _translate("Dialog", "False"))
        self.BottomComboBox.setItemText(0, _translate("Dialog", "True"))
        self.BottomComboBox.setItemText(1, _translate("Dialog", "False"))
        self.SolidComboBox.setItemText(0, _translate("Dialog", "True"))
        self.SolidComboBox.setItemText(1, _translate("Dialog", "False"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
