# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IndxedFaceSetDialogue.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class IndexeddFaceSetDialogue(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(False)
        Dialog.resize(600, 400)
        Dialog.setMinimumSize(QtCore.QSize(600, 400))
        Dialog.setMaximumSize(QtCore.QSize(600, 400))
        Dialog.setSizeGripEnabled(False)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.pointTableWidget = QtWidgets.QTableWidget(Dialog)
        self.pointTableWidget.setAlternatingRowColors(True)
        self.pointTableWidget.setColumnCount(5)
        self.pointTableWidget.setObjectName("pointTableWidget")
        self.pointTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.pointTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.pointTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.pointTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.pointTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.pointTableWidget.setHorizontalHeaderItem(4, item)
        self.pointTableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.pointTableWidget.horizontalHeader().setMinimumSectionSize(19)
        self.pointTableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.pointTableWidget.verticalHeader().setMinimumSectionSize(21)
        self.pointTableWidget.verticalHeader().setSortIndicatorShown(False)
        self.pointTableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.pointTableWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "IndexedFaceSet Node Dialogue"))
        item = self.pointTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Type"))
        item = self.pointTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Index 1"))
        item = self.pointTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Index 2"))
        item = self.pointTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Index 3"))
        item = self.pointTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Index 4"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
