# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Viewer(TreeWidget).ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from .TreeView import X3DTreeWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1012, 883)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Base = QtWidgets.QGroupBox(self.centralwidget)
        self.Base.setTitle("")
        self.Base.setObjectName("Base")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Base)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.Base)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.OpenButton = QtWidgets.QPushButton(self.groupBox)
        self.OpenButton.setObjectName("OpenButton")
        self.horizontalLayout_2.addWidget(self.OpenButton)
        self.VertexButton = QtWidgets.QPushButton(self.groupBox)
        self.VertexButton.setCheckable(True)
        self.VertexButton.setAutoRepeat(False)
        self.VertexButton.setAutoExclusive(False)
        self.VertexButton.setObjectName("VertexButton")
        self.horizontalLayout_2.addWidget(self.VertexButton)
        self.WireButton = QtWidgets.QPushButton(self.groupBox)
        self.WireButton.setCheckable(True)
        self.WireButton.setAutoRepeat(False)
        self.WireButton.setAutoExclusive(False)
        self.WireButton.setObjectName("WireButton")
        self.horizontalLayout_2.addWidget(self.WireButton)
        self.FaceButton = QtWidgets.QPushButton(self.groupBox)
        self.FaceButton.setCheckable(True)
        self.FaceButton.setChecked(True)
        self.FaceButton.setAutoRepeat(False)
        self.FaceButton.setAutoExclusive(False)
        self.FaceButton.setObjectName("FaceButton")
        self.horizontalLayout_2.addWidget(self.FaceButton)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.Base)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout.addWidget(self.groupBox_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 6)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.Base)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.treeWidget = X3DTreeWidget(self.groupBox_3)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.setHeaderLabel("")
        self.treeWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.verticalLayout_3.addWidget(self.treeWidget)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(1, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.Base, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1012, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionVertex = QtWidgets.QAction(MainWindow)
        self.actionVertex.setCheckable(True)
        self.actionVertex.setObjectName("actionVertex")
        self.actionWire = QtWidgets.QAction(MainWindow)
        self.actionWire.setCheckable(True)
        self.actionWire.setObjectName("actionWire")
        self.actionFace = QtWidgets.QAction(MainWindow)
        self.actionFace.setCheckable(True)
        self.actionFace.setObjectName("actionFace")
        self.actionFace.setChecked(True)
        self.actionFileOpen = QtWidgets.QAction(MainWindow)
        self.actionFileOpen.setObjectName("actionFileOpen")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionFileOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuView.addAction(self.actionVertex)
        self.menuView.addAction(self.actionWire)
        self.menuView.addAction(self.actionFace)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VR LAB"))
        self.OpenButton.setText(_translate("MainWindow", "FileOpen"))
        self.VertexButton.setText(_translate("MainWindow", "Vertex"))
        self.WireButton.setText(_translate("MainWindow", "Wire"))
        self.FaceButton.setText(_translate("MainWindow", "Face"))
        self.groupBox_2.setTitle(_translate("MainWindow", "View"))
        #self.groupBox_3.setTitle(_translate("MainWindow", "TreeView"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionVertex.setText(_translate("MainWindow", "Vertex"))
        self.actionWire.setText(_translate("MainWindow", "Wire"))
        self.actionFace.setText(_translate("MainWindow", "Face"))
        self.actionFileOpen.setText(_translate("MainWindow", "FileOpen"))
        self.actionClose.setText(_translate("MainWindow", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

